FROM python:3.12-slim-bookworm

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY . /workspace/fastapi

WORKDIR /workspace/fastapi
RUN uv sync

CMD [".venv/bin/fastapi", "run", "--host", "0.0.0.0"]
